name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --immutable --immutable-cache --check-cache
        working-directory: 3dcmetro-api
      - run: yarn deploy > /dev/null
        working-directory: 3dcmetro-api
      - run: yarn install --immutable --immutable-cache --check-cache
        working-directory: 3dcmetro-web
      - run: yarn build
        working-directory: 3dcmetro-web
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        working-directory: 3dcmetro-web
        with:
          branch: gh-pages
          folder: dist
          single-commit: true