name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: "API: Install"
        working-directory: 3dcmetro-api
        run: yarn install --immutable --immutable-cache --check-cache
      - name: "API: Deploy"
        working-directory: 3dcmetro-api
        run: yarn deploy > /dev/null
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: "Web: Install"
        working-directory: 3dcmetro-web-v2
        run: yarn install --immutable --immutable-cache --check-cache
      - name: "Web: Build"
        working-directory: 3dcmetro-web-v2
        run: yarn build
      - name: "Web: Deploy"
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: 3dcmetro-web-v2/dist
          single-commit: true
        if: ${{ github.ref == 'refs/heads/main' }}