name: Build and Deploy
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        working-directory: 3dcmetro-web
        run: |
          yarn install
          yarn build
      - name: Deploy
        working-directory: 3dcmetro-web
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          single-commit: true